improving Ubuntu init.d script and doing proper restarts again

diff --git a/templates/default/debian/jboss-init.erb b/templates/default/debian/jboss-init.erb
--- a/templates/default/debian/jboss-init.erb
+++ b/templates/default/debian/jboss-init.erb
@@ -1,49 +1,169 @@
-#!/bin/sh
+#!/bin/bash
+#
+# JBoss standalone control script
+#
 ### BEGIN INIT INFO
-# Provides:          jboss
-# Required-Start:    $local_fs $remote_fs $network $syslog
-# Required-Stop:     $local_fs $remote_fs $network $syslog
+# Provides:          jboss-as
+# Required-Start:    $local_fs $remote_fs $network
+# Required-Stop:     $local_fs $remote_fs $network
+# Should-Start:      $named
+# Should-Stop:       $named
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Start/Stop JBoss AS v7.0.0
+# Short-Description: Start JBoss AS
+# Description:       Start JBoss Application Server.
 ### END INIT INFO
 #
-#source some script files in order to set and export environmental variables
-#as well as add the appropriate executables to $PATH
-[ -r /etc/profile.d/java.sh ] && . /etc/profile.d/java.sh
-[ -r /etc/profile.d/jboss.sh ] && . /etc/profile.d/jboss.sh
 
-JBOSS_HOME=<%= node['jboss7']['jboss_home'] -%>
+#JBOSS_CONF="/opt/jboss-as-7/bin/init.d/jboss-as.conf"
 
-EAP_OPTS="-Djboss.server.log.dir=<%= node['jboss7']['log_dir'] -%> -Djboss.server.config.dir=<%= node['jboss7']['config_dir'] -%> -b 0.0.0.0 --server-config=standalone-full.xml"
+NAME=jboss
+DEFAULT=/etc/default/$NAME
+
+# Source function library.
+. /lib/lsb/init-functions
+
+# Load Java configuration.
+# Ubuntu has it in /etc/default
+[ -r /etc/default/java ] && . /etc/default/java
+export JAVA_HOME
+
+# Set defaults.
+
+if [ -z "$JBOSS_HOME" ]; then
+  JBOSS_HOME=<%= node['jboss7']['jboss_home'] -%>
+fi
+export JBOSS_HOME
+
+if [ -z "$JBOSS_USER" ]; then
+  JBOSS_USER="<%= node['jboss7']['jboss_user'] -%>" 
+fi
+export JBOSS_USER
+
+if [ -z "$JBOSS_PIDFILE" ]; then
+  JBOSS_PIDFILE=/var/run/$NAME/jboss-as-standalone.pid
+fi
+export JBOSS_PIDFILE
+
+if [ -z "$JBOSS_CONSOLE_LOG" ]; then
+  JBOSS_CONSOLE_LOG=/var/log/$NAME/console.log
+fi
+
+# We need this to be set to get a pidfile !
+if [ -z "$LAUNCH_JBOSS_IN_BACKGROUND" ]; then
+  LAUNCH_JBOSS_IN_BACKGROUND=true
+fi
+export LAUNCH_JBOSS_IN_BACKGROUND
+
+if [ -z "$STARTUP_WAIT" ]; then
+  STARTUP_WAIT=120
+fi
+
+if [ -z "$SHUTDOWN_WAIT" ]; then
+  SHUTDOWN_WAIT=120
+fi
+
+if [ -z "$JBOSS_CONFIG" ]; then
+  JBOSS_CONFIG=standalone-full.xml
+fi
+
+JBOSS_SCRIPT=$JBOSS_HOME/bin/standalone.sh
+
+MATCHING_ARGS=(--user "$JBOSS_USER" --pidfile "$JBOSS_PIDFILE")
+
+start() {
+  log_daemon_msg "Starting $NAME"
+  id $JBOSS_USER > /dev/null 2>&1
+  if [ $? -ne 0 -o -z "$JBOSS_USER" ]; then
+    log_failure_msg "User $JBOSS_USER does not exist..."
+    log_end_msg 1
+    exit 1
+  fi
+
+  mkdir -p $(dirname $JBOSS_CONSOLE_LOG)
+  cat /dev/null > $JBOSS_CONSOLE_LOG
+  chown $JBOSS_USER $JBOSS_CONSOLE_LOG
+
+  mkdir -p $(dirname $JBOSS_PIDFILE)
+  chown ${JBOSS_USER}: $(dirname $JBOSS_PIDFILE) || true
+
+  if [ ! -z "$JBOSS_USER" ]; then
+    start-stop-daemon --start ${MATCHING_ARGS[@]} --oknodo --chuid "$JBOSS_USER" --chdir "$JBOSS_HOME" --retry $STARTUP_WAIT $(if [ "$LAUNCH_JBOSS_IN_BACKGROUND" == "true" ] ; then echo "--background" ; fi) --startas /bin/bash -- -c "exec $JBOSS_SCRIPT -c $JBOSS_CONFIG 2>&1 > $JBOSS_CONSOLE_LOG"
+  else
+    log_failure_msg "Error: Environment variable JBOSS_USER not set or empty."
+    log_end_msg 1
+    exit 1
+  fi
+
+  if [ "$LAUNCH_JBOSS_IN_BACKGROUND" == "true" ] ; then
+    count=0
+    launched_status=1
+
+    until [ $count -gt $STARTUP_WAIT ]
+    do
+      grep 'JBAS015874:' $JBOSS_CONSOLE_LOG > /dev/null
+      if [ $? -eq 0 ] ; then
+        launched_status=0
+        break
+      fi
+      sleep 1
+      let count=$count+1;
+    done
+
+    log_end_msg $launched_status
+    return $launched_status
+  else
+    log_end_msg $?
+    return $?
+  fi
+}
+
+stop() {
+  log_daemon_msg "Stopping $NAME"
+
+  END_STATUS=0
+  if [ -f $JBOSS_PIDFILE ]; then
+    start-stop-daemon --stop ${MATCHING_ARGS[@]} --retry $SHUTDOWN_WAIT
+    END_STATUS=$?
+    rm -f $JBOSS_PIDFILE
+  fi
+  log_end_msg $END_STATUS
+  return $END_STATUS
+}
+
+status() {
+    if [ -f $JBOSS_PIDFILE ]; then
+      read ppid < $JBOSS_PIDFILE
+      if [ `ps --pid $ppid 2> /dev/null | grep -c $ppid 2> /dev/null` -eq '1' ]; then
+        echo "$prog is running (pid $ppid)"
+        return 0
+      else
+        echo "$prog dead but pid file exists"
+        return 1
+      fi
+    fi
+    echo "$prog is not running"
+    return 3
+}
+
 case "$1" in
-    start)
-        echo "Starting EAP AS 6.4.0"
-        #original:
-        #sudo -u jboss sh ${JBOSS_HOME}/bin/standalone.sh
-
-        #updated:
-        start-stop-daemon --start --quiet --background --chuid jboss7 --exec ${JBOSS_HOME}/bin/standalone.sh -- $EAP_OPTS
-    ;;
-    stop)
-        echo "Stopping JBoss EAP AS 6.4.0"
-        #original:
-        #sudo -u jboss sh ${JBOSS_HOME}/bin/jboss-admin.sh --connect command=:shutdown
-
-        #updated:
-        start-stop-daemon --start --quiet --background --chuid jboss7 --exec ${JBOSS_HOME}/bin/jboss-cli.sh -- --connect command=:shutdown
-    ;;
-    restart)
-        echo "Stopping JBoss EAP AS 6.4.0"
-        start-stop-daemon --start --quiet --background --chuid jboss7 --exec ${JBOSS_HOME}/bin/jboss-cli.sh -- --connect command=:shutdown
-
-        echo "Starting JBoss EAP AS 6.4.0"
-        start-stop-daemon --start --quiet --background --chuid jboss7 --exec ${JBOSS_HOME}/bin/standalone.sh -- $EAP_OPTS
-    ;;
-    *)
-        echo "Usage: /etc/init.d/jboss {start|stop|restart}"
-        exit 1
-    ;;
+  start)
+      start
+      ;;
+  stop)
+      stop
+      ;;
+  restart)
+      $0 stop
+      $0 start
+      ;;
+  status)
+      status
+      ;;
+  *)
+      ## If no parameters are given, print which are avaiable.
+      echo "Usage: $0 {start|stop|status|restart}"
+      exit 1
+      ;;
 esac
 
-exit 0
